// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var com = com || {};

/**
 * @const
 * @namespace
 */
com.banca = com.banca || {};

/**
 * @const
 * @namespace
 */
com.banca.game = com.banca.game || {};

/**
 * @const
 * @namespace
 */
com.banca.game.protocols = com.banca.game.protocols || {};

/**
 * @const
 * @namespace
 */
com.banca.game.protocols.common = com.banca.game.protocols.common || {};

/**
 * @const
 * @namespace
 */
com.banca.game.protocols.request = com.banca.game.protocols.request || {};

/**
 * @constructor
 */
com.banca.game.protocols.request.LoginRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {com.banca.game.protocols.request.LoginRequest}
 */
com.banca.game.protocols.request.LoginRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {com.banca.game.protocols.request.LoginRequest=} obj
 * @returns {com.banca.game.protocols.request.LoginRequest}
 */
com.banca.game.protocols.request.LoginRequest.getRootAsLoginRequest = function(bb, obj) {
  return (obj || new com.banca.game.protocols.request.LoginRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
com.banca.game.protocols.request.LoginRequest.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
com.banca.game.protocols.request.LoginRequest.prototype.password = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
com.banca.game.protocols.request.LoginRequest.startLoginRequest = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
com.banca.game.protocols.request.LoginRequest.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} passwordOffset
 */
com.banca.game.protocols.request.LoginRequest.addPassword = function(builder, passwordOffset) {
  builder.addFieldOffset(1, passwordOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
com.banca.game.protocols.request.LoginRequest.endLoginRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
com.banca.game.protocols.request.QuickJoinRoomRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {com.banca.game.protocols.request.QuickJoinRoomRequest}
 */
com.banca.game.protocols.request.QuickJoinRoomRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {com.banca.game.protocols.request.QuickJoinRoomRequest=} obj
 * @returns {com.banca.game.protocols.request.QuickJoinRoomRequest}
 */
com.banca.game.protocols.request.QuickJoinRoomRequest.getRootAsQuickJoinRoomRequest = function(bb, obj) {
  return (obj || new com.banca.game.protocols.request.QuickJoinRoomRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
com.banca.game.protocols.request.QuickJoinRoomRequest.prototype.bet = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {com.banca.game.protocols.common.RoomType}
 */
com.banca.game.protocols.request.QuickJoinRoomRequest.prototype.roomType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {com.banca.game.protocols.common.RoomType} */ (this.bb.readInt8(this.bb_pos + offset)) : com.banca.game.protocols.common.RoomType.BanCaRoom;
};

/**
 * @param {flatbuffers.Builder} builder
 */
com.banca.game.protocols.request.QuickJoinRoomRequest.startQuickJoinRoomRequest = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} bet
 */
com.banca.game.protocols.request.QuickJoinRoomRequest.addBet = function(builder, bet) {
  builder.addFieldInt32(0, bet, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {com.banca.game.protocols.common.RoomType} roomType
 */
com.banca.game.protocols.request.QuickJoinRoomRequest.addRoomType = function(builder, roomType) {
  builder.addFieldInt8(1, roomType, com.banca.game.protocols.common.RoomType.BanCaRoom);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
com.banca.game.protocols.request.QuickJoinRoomRequest.endQuickJoinRoomRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
com.banca.game.protocols.request.JoinRoomRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {com.banca.game.protocols.request.JoinRoomRequest}
 */
com.banca.game.protocols.request.JoinRoomRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {com.banca.game.protocols.request.JoinRoomRequest=} obj
 * @returns {com.banca.game.protocols.request.JoinRoomRequest}
 */
com.banca.game.protocols.request.JoinRoomRequest.getRootAsJoinRoomRequest = function(bb, obj) {
  return (obj || new com.banca.game.protocols.request.JoinRoomRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
com.banca.game.protocols.request.JoinRoomRequest.prototype.roomId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
com.banca.game.protocols.request.JoinRoomRequest.startJoinRoomRequest = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} roomId
 */
com.banca.game.protocols.request.JoinRoomRequest.addRoomId = function(builder, roomId) {
  builder.addFieldInt32(0, roomId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
com.banca.game.protocols.request.JoinRoomRequest.endJoinRoomRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
com.banca.game.protocols.request.Shoot = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {com.banca.game.protocols.request.Shoot}
 */
com.banca.game.protocols.request.Shoot.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {com.banca.game.protocols.request.Shoot=} obj
 * @returns {com.banca.game.protocols.request.Shoot}
 */
com.banca.game.protocols.request.Shoot.getRootAsShoot = function(bb, obj) {
  return (obj || new com.banca.game.protocols.request.Shoot).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
com.banca.game.protocols.request.Shoot.prototype.bulletType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
com.banca.game.protocols.request.Shoot.prototype.fishType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
com.banca.game.protocols.request.Shoot.startShoot = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} bulletType
 */
com.banca.game.protocols.request.Shoot.addBulletType = function(builder, bulletType) {
  builder.addFieldInt8(0, bulletType, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} fishType
 */
com.banca.game.protocols.request.Shoot.addFishType = function(builder, fishType) {
  builder.addFieldInt8(1, fishType, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
com.banca.game.protocols.request.Shoot.endShoot = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.com = com;
