// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var com = com || {};

/**
 * @const
 * @namespace
 */
com.banca = com.banca || {};

/**
 * @const
 * @namespace
 */
com.banca.game = com.banca.game || {};

/**
 * @const
 * @namespace
 */
com.banca.game.protocols = com.banca.game.protocols || {};

/**
 * @const
 * @namespace
 */
com.banca.game.protocols.common = com.banca.game.protocols.common || {};

/**
 * @const
 * @namespace
 */
com.banca.game.protocols.response = com.banca.game.protocols.response || {};

/**
 * @constructor
 */
com.banca.game.protocols.response.LoginSuccessResponse = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {com.banca.game.protocols.response.LoginSuccessResponse}
 */
com.banca.game.protocols.response.LoginSuccessResponse.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {com.banca.game.protocols.response.LoginSuccessResponse=} obj
 * @returns {com.banca.game.protocols.response.LoginSuccessResponse}
 */
com.banca.game.protocols.response.LoginSuccessResponse.getRootAsLoginSuccessResponse = function(bb, obj) {
  return (obj || new com.banca.game.protocols.response.LoginSuccessResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {com.banca.game.protocols.common.User=} obj
 * @returns {com.banca.game.protocols.common.User|null}
 */
com.banca.game.protocols.response.LoginSuccessResponse.prototype.user = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new com.banca.game.protocols.common.User).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
com.banca.game.protocols.response.LoginSuccessResponse.startLoginSuccessResponse = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} userOffset
 */
com.banca.game.protocols.response.LoginSuccessResponse.addUser = function(builder, userOffset) {
  builder.addFieldOffset(0, userOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
com.banca.game.protocols.response.LoginSuccessResponse.endLoginSuccessResponse = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
com.banca.game.protocols.response.JoinRoomSuccessResponse = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {com.banca.game.protocols.response.JoinRoomSuccessResponse}
 */
com.banca.game.protocols.response.JoinRoomSuccessResponse.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {com.banca.game.protocols.response.JoinRoomSuccessResponse=} obj
 * @returns {com.banca.game.protocols.response.JoinRoomSuccessResponse}
 */
com.banca.game.protocols.response.JoinRoomSuccessResponse.getRootAsJoinRoomSuccessResponse = function(bb, obj) {
  return (obj || new com.banca.game.protocols.response.JoinRoomSuccessResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
com.banca.game.protocols.response.JoinRoomSuccessResponse.prototype.roomId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
com.banca.game.protocols.response.JoinRoomSuccessResponse.prototype.bet = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
com.banca.game.protocols.response.JoinRoomSuccessResponse.prototype.currentTimeMillis = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
com.banca.game.protocols.response.JoinRoomSuccessResponse.startJoinRoomSuccessResponse = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} roomIdOffset
 */
com.banca.game.protocols.response.JoinRoomSuccessResponse.addRoomId = function(builder, roomIdOffset) {
  builder.addFieldOffset(0, roomIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} bet
 */
com.banca.game.protocols.response.JoinRoomSuccessResponse.addBet = function(builder, bet) {
  builder.addFieldInt32(1, bet, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} currentTimeMillis
 */
com.banca.game.protocols.response.JoinRoomSuccessResponse.addCurrentTimeMillis = function(builder, currentTimeMillis) {
  builder.addFieldInt64(2, currentTimeMillis, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
com.banca.game.protocols.response.JoinRoomSuccessResponse.endJoinRoomSuccessResponse = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
com.banca.game.protocols.response.ErrorResponse = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {com.banca.game.protocols.response.ErrorResponse}
 */
com.banca.game.protocols.response.ErrorResponse.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {com.banca.game.protocols.response.ErrorResponse=} obj
 * @returns {com.banca.game.protocols.response.ErrorResponse}
 */
com.banca.game.protocols.response.ErrorResponse.getRootAsErrorResponse = function(bb, obj) {
  return (obj || new com.banca.game.protocols.response.ErrorResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
com.banca.game.protocols.response.ErrorResponse.prototype.code = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
com.banca.game.protocols.response.ErrorResponse.prototype.message = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
com.banca.game.protocols.response.ErrorResponse.startErrorResponse = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} code
 */
com.banca.game.protocols.response.ErrorResponse.addCode = function(builder, code) {
  builder.addFieldInt32(0, code, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} messageOffset
 */
com.banca.game.protocols.response.ErrorResponse.addMessage = function(builder, messageOffset) {
  builder.addFieldOffset(1, messageOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
com.banca.game.protocols.response.ErrorResponse.endErrorResponse = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.com = com;
